### ISSUE TITLE
原作者的commits全部消除掉了

### ISSUE THREAD

**Issue by shithead548** [Yam-cn/pyalgotrade-cn#1]
为什么原作者的commits全部消除掉了，能不能加上去，这样对比能看出你改了哪些地方，代码好看点

**Comment by chopchopjames** [comment]
修改的部分都加了备注，我不太清楚怎么把作者的commit加进来，刚开始玩git，研究一下，弄明白了之后我会加上来的。

**Comment by chopchopjames** [comment]
现在cn的文件已经统一合并到cn文件夹里面
