### ISSUE TITLE
0.18版本后，如何获取day数据？

### ISSUE THREAD

**Issue by Rex-Diego** [Yam-cn/pyalgotrade-cn#10]
看到day数据的样品里有600288，600289两只，里面有bought_amount和sold_amount，也看到tick数据里也是这两支样品。所以day数据是从tick里面抽取出来的吗？项目里有发布抽取函数吗？

另外setup.py的版本号依然是0.17，而且需要在package里加一句 'pyalgotrade.cn'才可以。

**Comment by chopchopjames** [comment]
谢谢，setup.py的bug群里已经有fix，晚些时候我会update上去。

day数据是单独的数据，不是抽取的，如果需要周期转换，可以使用一下pandas的convert功能。下一个版本考虑加入周期转换的功能。
