### ISSUE TITLE
如何回测多只股票组合？并显示组合的收益曲线

### ISSUE THREAD

**Issue by panlei86** [Yam-cn/pyalgotrade-cn#6]
我看现在策略实例里面都是回测单只股票的例子，但实际我们交易的时候，更多的情况下要管理多只股票的组合。 所以组合的回测更重要，不知道pyalgotrade-cn能否实现这个功能？ 有示例代码?

**Comment by fanchangyong** [comment]
`feed.addBarsFromCSV`，你用这个函数添加其他股票就可以了。
