### ISSUE TITLE
如何用当前Bar的价格成交，而不是用下一根Bar？

### ISSUE THREAD

**Issue by fanchangyong** [Yam-cn/pyalgotrade-cn#9]
各位兄弟们，我在原版的pyalgotrade底下提了个issue，但不知道有没有理我。
大家有没有知道这个问题的解决方案，或者什么原因机制要做成必须用下一根Bar的价格成交？
希望给解释一下，谢谢。
https://github.com/gbeced/pyalgotrade/issues/77

**Comment by snake3342** [comment]
well，在实盘的时候，假设我们现在是9:35分，使用的是15分钟bar，你backtest的时候如果在9:35使用本bar的close，你就相当于读取了未来数据——9:45的价格。当然是不应该的吧？

**Comment by chopchopjames** [comment]
@snake3342 正解

**Comment by geraybos** [comment]
事实上我觉得 @fanchangyong 的需求是有意义的，虽然我不知道在目前的框架下如何实现。也就是说基本上只把bar看作在结束时刻的一个以close成交的trade，并且马上下单的话以该close成交，或者以close+slippage成交。否则如果以下一个open成交的话滑点太大。 @chopchopjames @snake3342
